shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2010
  - TOOLSET: vs2013
  - TOOLSET: vs2015

configuration:
  - Debug
  - Release

install:
  - nuget restore voorhees.sln

build:
  project: voorhees.sln

after_test:
  - packages\NUnit.Console.3.0.1\tools\nunit3-console.exe voorhees_tests\bin\Release\voorhees_tests.dll

