name: Generate Code Coverage and Upload to Coveralls

on: 
  - push
  - pull_request

jobs:
  code-coverage:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: rlespinasse/git-commit-data-action@v1
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
      - run: dotnet new tool-manifest
      - name: install Coveralls.net
        run: dotnet tool install --local coveralls.net
      - name: Generate Coverage Report
        run: dotnet test --collect:"XPlat Code Coverage" -r . -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload to coveralls
        run: Get-ChildItem -Path . -Recurse coverage.opencover.xml | % {dotnet tool run csmacnz.Coveralls --opencover -i $_.FullName --repoToken ${{ secrets.COVERALLS_TOKEN }} --useRelativePaths --commitId ${{ env.GITHUB_SHA }} --commitBranch ${{ github.ref_name }} --commitAuthor "${{ env.GIT_COMMIT_AUTHOR_NAME }}" --commitEmail "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}" --commitMessage "${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}" --jobId ${{ github.run_number }} --serviceName github}